### ISSUE TITLE
Première commande /members en erreur

### ISSUE THREAD

**Issue by voXrey** [prepas-mp2i/mp2i-discord-bot#12]
Lorsque l'on exécute la commande /members pour la première fois sur une CPGE ou une Ecole, il y a souvent une erreur non gérée par le bot.
La deuxième fois tout semble fonctionner.

![image](https://github.com/user-attachments/assets/05c6fcb3-12fc-41ca-9f05-86df130a4feb)

**Comment by ajayat** [comment]
Bonjour, je viens de checker les logs,  la commande `ctx.reply` génère de temps en temps cette erreur :
`NotFound: 404 Not Found (error code: 10062): Unknown interaction`

C''est dû à un timeout côté API Discord (qui est de 3s), vu que le VPS est peu puissant. La fois suivante, il doit y avoir du cache.
J'ai la possibilité de retarder la réponse avec defer(), je vais tester ça.

**Comment by ajayat** [comment]
Malheureusement, le problème vient de l'API Discord, j'ai essayé de les retarder, il devrait y avoir un peu moins de commandes qui se font timeout.
En attendant de trouver une solution 100% fonctionnelle, il est toujours possible de faire les commandes classiques en les préfixant avec `=` (exemple: =help), sans timeout
